---

- name: check for old docker versions
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: dependency check
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: add docker apt key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: add docker repo
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
