--- 
- become: true
  hosts: servers
  name: "playbook for server vm"
  roles: 
    - role: software/consul
    - role: software/nomad

- become: true
  hosts: clients
  name: "playbook for client vm"
  roles: 
    - role: software/docker
    - role: software/consul
    - role: software/nomad

