- name: reload consul configuration on Linux
  command: "pkill --pidfile '{{ consul_run_path }}/consul.pid' --signal SIGHUP"
  when: ansible_os_family != "Windows"
  listen: 'reload consul configuration'